Add JavaScript to menu
Franky237/finish-mobile-version pull request #7
Opened 2022-11-15 11:29 UTC by Franky237

- Added simple JavaScript to the menu
- Added click option to display nav items
- Added click option to close nav items
- Added click option to redirect to the area on the page

2022-11-15 11:49 UTC, christianbiring1 requested changes
Hi @Franky237 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![almost](https://user-images.githubusercontent.com/97100091/201912037-26315f10-5dc9-40e6-9a87-20c40ad3f258.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `summary` :+1: 
- [ ] Good commit history.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Giving your PR a descriptive PR `title`
`hint: Mobile menu would sound great than Add JavaScript to menu.`
- Also, make sure your design both desktop and mobile look similar to the ones provided in Figma.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 11:49 UTC, christianbiring1 commented on style.css
>  }
- [ ] For a great user experience, kindly make sure you stick to the design as much as possible. (typos, spacing, color)

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201910509-1f241b2d-376d-4cd0-8f13-b737504e60f3.png)
Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201910888-b8e4dba1-ec6e-423e-ba5b-98a8511b54cd.png)

2022-11-15 11:49 UTC, christianbiring1 commented on style.css
>      padding: auto;
- [ ] Kindly stick to the design as much as possible. for a better user experience. 
`hint: You may consider adding the font of your elements and readjust the placement of elements on your page.`

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201911093-3b822158-e53c-4845-b782-12fb2df310a1.png)

Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201911182-a8c9dad2-b72e-434a-b563-c4ea80cab728.png)

2022-11-15 11:49 UTC, christianbiring1 commented on style.css
>  .navbar {
- [ ] Kindly make sure you stick to the design as much as possible.
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201911597-90a57db4-ee37-4eec-928b-95f19def6c39.png)
Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201911686-84765b4f-7e89-424b-93f6-f0a60d8b0f35.png)

2022-11-16 13:33 UTC, mckent05 approved these changes
Hi @Franky237,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/202193839-e0a7bd4c-6baa-4995-b619-2a85945eac23.gif)


## Highlights
- All linter checks are passing ✔️ 
- Good job making changes suggested by previous reviewer 👍 

## Optional suggestions
- Your project (mobile version) has a  scroll on the x-axis, please fix this 🙏 

Your project:
<img width="446" alt="dgn" src="https://user-images.githubusercontent.com/73607512/202194110-c0157ed2-49ef-441c-9dd6-1ae732198b88.PNG">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 13:55 UTC, merged